# Generated by Django 3.2.9 on 2022-05-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='don',
            name='review',
            field=models.CharField(blank=True, max_length=243, null=True),
        ),
        migrations.AddField(
            model_name='nongo',
            name='review',
            field=models.CharField(blank=True, max_length=243, null=True),
        ),
    ]
