# Generated by Django 4.0.4 on 2022-05-09 19:16

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_statements', models.FileField(upload_to='documents')),
                ('reports', models.FileField(upload_to='documents')),
                ('amount_range', models.IntegerField(blank=True, default=0, null=True)),
                ('verification', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_Donor',
            new_name='is_Don',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_administrator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_NGO',
        ),
        migrations.AddField(
            model_name='user',
            name='is_NonGo',
            field=models.BooleanField(default=False, verbose_name='Is Ngo'),
        ),
        migrations.CreateModel(
            name='NonGo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=243, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ngo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('logo', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='images')),
                ('category', models.TextField()),
                ('description', models.TextField(max_length=200)),
                ('web_link', models.URLField(max_length=300)),
                ('contact', models.IntegerField(blank=True, default=0, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ngo_request', to='charitable.requests')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('logo', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='images')),
                ('type', models.BooleanField()),
                ('web_link', models.URLField(max_length=300)),
                ('contact', models.IntegerField(blank=True, default=0, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_request', to='charitable.requests')),
            ],
        ),
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Don_name', models.CharField(max_length=254, null=True)),
                ('contact', models.IntegerField(blank=True, default=0, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=243, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=243, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('requests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='charitable.requests')),
            ],
        ),
    ]
