# Generated by Django 4.0.4 on 2022-05-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_NGO',
        ),
        migrations.AddField(
            model_name='user',
            name='is_Ngo',
            field=models.BooleanField(default=False, verbose_name='Is Ngo'),
        ),
    ]
