# Generated by Django 3.2.9 on 2022-05-05 19:45

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0002_remove_user_is_ngo_user_is_ngo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_statements', models.FileField(upload_to='documents')),
                ('reports', models.FileField(upload_to='documents')),
                ('amount_range', models.IntegerField(blank=True, default=0, null=True)),
                ('verification', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('logo', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='images')),
                ('category', models.TextField()),
                ('description', models.TextField(max_length=200)),
                ('web_link', models.URLField(max_length=300)),
                ('contact', models.IntegerField(blank=True, default=0, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ngo_request', to='charitable.requests')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('logo', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='images')),
                ('type', models.BooleanField()),
                ('web_link', models.URLField(max_length=300)),
                ('contact', models.IntegerField(blank=True, default=0, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_request', to='charitable.requests')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('requests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='charitable.requests')),
            ],
        ),
    ]
