# Generated by Django 3.2.9 on 2022-05-08 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0004_auto_20220508_1912'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administrator',
            new_name='Adminstrator',
        ),
    ]
