# Generated by Django 3.2.9 on 2022-05-08 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0005_rename_administrator_adminstrator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adminstrator',
            new_name='Administrator',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_adminstrator',
            new_name='is_administrator',
        ),
    ]
